from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
	login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
)

urlpatterns = [
	url(r'^home$', views.home, name='home'),
    url(r'^login$', login, {'template_name': 'apps/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'apps/logout.html'}),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
	url(r'^pengguna$', views.pengguna, name='pengguna'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^reset-password/$', password_reset, name='reset_password'),
    url(r'^reset-password/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    password_reset_confirm, name='reset_password_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete, name='reset_password_complete'),

 	#RESERVASI TOUR
 	url(r'^pesan_reservasi$', views.pesan_reservasi),
	url(r'^pesan_reservasi_baru/(?P<id>\d+)$', views.pesan_reservasi_baru, name='pesanreservasibaru'),
	url(r'^simpan_pesanan$', views.simpan_pesanan),
	url(r'^pesan_tour$', views.Pemesanan_tour),
	url(r'^pesan_sukses$', views.pesan_sukses),

	#CLIENT SIDE
	url(r'^$', views.index),
	url(r'^destination.html$', views.destination),
	url(r'^booking.html$', views.booking),
	url(r'^gallery1.html$', views.gallery1),
	url(r'^gallery2.html$', views.gallery2),
	url(r'^about.html$', views.about),
	url(r'^contact.html$', views.contact),
	#url(r'^login.html$', views.login),
	#url(r'^signup.html$', views.signup),
	url(r'^bali.html$', views.bali),
	url(r'^bandung.html$', views.bandung),
	url(r'^lombok.html$', views.lombok),
	url(r'^medan.html$', views.medan),
	url(r'^solo.html$', views.solo),
	url(r'^yogyakarta.html$', views.yogyakarta),
	url(r'^b1.html$', views.bali1),
	url(r'^b2.html$', views.bali2),
	url(r'^b3.html$', views.bali3),
	url(r'^b4.html$', views.bali4),
	url(r'^bdg1.html$', views.bdg1),
	url(r'^bdg2.html$', views.bdg2),
	url(r'^bdg3.html$', views.bdg3),
	url(r'^bdg4.html$', views.bdg4),
	url(r'^l1.html$', views.lombok1),
	url(r'^l2.html$', views.lombok2),
	url(r'^l3.html$', views.lombok3),
	url(r'^l4.html$', views.lombok4),
	url(r'^m1.html$', views.medan1),
	url(r'^m2.html$', views.medan2),
	url(r'^m3.html$', views.medan3),
	url(r'^m4.html$', views.medan4),
	url(r'^s1.html$', views.solo1),
	url(r'^s2.html$', views.solo2),
	url(r'^y1.html$', views.yogyakarta1),
	url(r'^y2.html$', views.yogyakarta2),
	url(r'^y3.html$', views.yogyakarta3),
	#DATA PRODUK
	url(r'^dataproduk$', views.dataproduk, name='dataproduk'),
	url(r'^input$', views.input),	
	url(r'^input_reservasi$', views.input_reservasi),	
	url(r'^simpan1$', views.simpan1),
	url(r'^simpan2$', views.simpan2),	
	url(r'^delete/(?P<id>\d+)$', views.delete),
	url(r'^edit_data_destinasi/(?P<id>\d+)$', views.edit_data_destinasi),
	url(r'^delete_destinasi/(?P<id>\d+)$', views.delete_destinasi),
	url(r'^edit_data_reservasi/(?P<id>\d+)$', views.edit_data_reservasi),
	url(r'^data$', views.data_client, name='data1'),
	url(r'^data2/(?P<id>\d+)$', views.data2, name='data2'),
	url(r'^data3/(?P<id>\d+)$', views.data3, name='data3'),
	url(r'^ganti_reservasi/(?P<id>\d+)$', views.ganti_reservasi),
	url(r'^ganti_destinasi/(?P<id>\d+)$', views.ganti_destinasi),
]
