# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesan_Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Depan', models.CharField(max_length=50)),
                ('Nama_Belakang', models.CharField(max_length=100)),
                ('Waktu_Berangkat', models.CharField(max_length=10)),
                ('Waktu_Pulang', models.CharField(max_length=10)),
                ('Paket', models.CharField(max_length=100)),
                ('Jumlah_Pax', models.IntegerField(default=0)),
                ('Dibuat_Pada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
