# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_pesan_tour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destinasi',
            new_name='Kota',
        ),
    ]
