# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20170915_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservasi',
            new_name='Produk',
        ),
    ]
