# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20170915_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pesan_Tour',
            new_name='Reservasi',
        ),
    ]
